name: Render and Commit Graphviz Diagram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  render-and-commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install graphviz

    # Step 4: Render the diagram
    - name: Render diagram
      run: |
        python /app/src/graphs.py

    # Step 5: Commit changes to the repository
    - name: Commit and push generated diagrams
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./img/
        git commit -m "Update generated diagrams [skip ci]" || echo "No changes to commit"
        git push
